### ISSUE TITLE
Implementation of Semantic Version Numbering for updates

### ISSUE THREAD

**Issue by DeathByKorea** [broke-protocol/issues#119]
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

So for BP, a convention would be 

6.0.0pre2 for 0.66 test 2 as it is a major version pre release

**Comment by BrokeProtocol** [comment]
I like the major/minor labels to separate major and minor bugs, however the version system you have proposed is confusing to me.

**Comment by UserR00T** [comment]
We've considered this option a while back but this will make it less appealing in change logs. Thus, we decided to not use sem versioning.
