### ISSUE TITLE
Loot drops with new electronics

### ISSUE THREAD

**Issue by YouRock379** [broke-protocol/issues#138]
It would be awesome if NPC often, or at least rarely, spawn with electronics that would be reasonable to have on them such as Tablets and Smartphones. For realism, more smartphones, but those are a bit pricey, so people would be getting rich off of them quick. If you want it to be implemented, but still make it a bit difficult to build up wealth, more tablets.

**Comment by DarkRosanne** [comment]
I like this idea but make it a bit rare that they drop them, but maybe make it a bit more common to find if you search them.
