### ISSUE TITLE
Username blacklist and whitelist

### ISSUE THREAD

**Issue by iwanPlays** [broke-protocol/issues#156]
Admins need the feature to blacklist usernames to prevent from logging in and from being created. Ideally with regex and ideally with an additional whitelist, which would allow certain usernames. For example I would blacklist:
[iI][wW][aA][nN][pP][lL][aA][Yy][sS]
[iI][vV][vV][aA][nN][pP][lL][aA][Yy][sS]
[hH][iI1][tT1][lL7][e3E][rR]

But after having created my account, I would whitelist:
iwanPlays

Alternatively the blacklist would only apply to non-admins.

**Comment by UserR00T** [comment]
We've decided that this feature will not be implemented into the base game. This can still however be implemented using a plugin.
