### ISSUE TITLE
Apartments - Make a "Do you really want to sell your apartment?" dialog

### ISSUE THREAD

**Issue by UserR00T** [broke-protocol/issues#163]
I just accidentally sold my apartment because i tried to click enter and scrolled down.

Lost like 5k, alot of guns, ammo, (riot) clothes, melees bombs etc..

Its more my fault but a confirm dialog would be handy

**Comment by UserR00T** [comment]
Has been added in the plugin ['BP:Essentials'.](https://github.com/UserR00T/BP-Essentials)

**Comment by UserR00T** [comment]
Reopening because this should be in the base game too.

**Comment by stabbykat** [comment]
Hopefully this can be added soon, I've accidentally sold my apartment too many times with all my stuff in it gone every time
