### ISSUE TITLE
client serial and banning system

### ISSUE THREAD

**Issue by ghost** [broke-protocol/issues#190]
Hello i would like to suggest adding something like a serial to game client which will help administrators in banning people. I already banned one dude like 20 times in a row and he just keeped coming back because he was able to change his ip so easily with just unplugging his usb modem. 
So i suggest creating something like Multi Theft Auto has for really long time
https://wiki.multitheftauto.com/wiki/BanPlayer
https://wiki.multitheftauto.com/wiki/Serial
https://wiki.multitheftauto.com/wiki/GetPlayerSerial

Why use something like this? MTA does very good job on preventing hacking on their servers so i think that we should look into every thing that is useful for us and implement it in our own way :P MTA is open source too so its not hard to do so in a way not violating license

**Comment by BrokeProtocol** [comment]
You can range ban their IP within your firewall something like this: 76.48.39.0/24

**Comment by UserR00T** [comment]
1.0 Will now fully have SteamID support which can be used to ban by steam id.
