### ISSUE TITLE
Server Moderator

### ISSUE THREAD

**Issue by ekcja** [broke-protocol/issues#194]
Since there are administrators for the servers in Broke Protocol, why not add moderators too? My point is that administrators have access to all commands, and moderators have access to less commands like kick or teleport but not ban, it could really help moderate server, commands abuse would impact on people lighter etc.

**Comment by Miguimops021** [comment]
And more commands for admins and moders!!!!!

**Comment by UserR00T** [comment]
We now utilize a groups.json file which allows you to create custom groups for whoever with whatever permissions. This means that you can have both a Moderator and Admin group.
