### ISSUE TITLE
New Jobs. Buy buildings, etc.

### ISSUE THREAD

**Issue by ekcja** [broke-protocol/issues#195]
-Jobs-
Mechanic - Can repair vehicles and get's money every time he repairs a car that was damaged.
Restaurant Worker - Can serve food to NPC's that would come to the restaurant, for example, an NPC would go to restaurant and would show that He wants some burger and water, then you would have to find and click/collect burger and water then go back to him and sell him it for an X amount of money.
Hitman - Could take hits from players and rich NPC's, like shooting X gang member of X gang or some NPC in certain location that isn't moving, after the hit the player would get a reward of X money [Depends how much person who made a hit paid for it]. 
Professional Drug Dealer - Would sell drugs and have discount on buying the seeds for drugs.
Police Commander/Chief - Can make an announcement on top of the screen with his own custom message, can also order other policemen and fire them out of the job if they have at least 1+ star with a small cooldown of 1-2 minutes.
-Buildings-
***RESTAURANTS*** 10k$, 750$ per minute, can be robbed and if it will be it will stop making money for 5 minutes resulting in loss of almost 4k$ unless the robbery would be stopped by killing the one who is robbing it.
***COFFEE SHOP*** 5k$ 300$ per minute, can be also robbed and if it will be then it will stop making money for 3 minutes resulting in loss of 900$ unless the robbery would be stopped by killing the one who is robbing it.
***PAWN SHOP/ELECTRONICS SHOP*** 7,5k$ 500$ per minute, if it will be robbed then it will stop making money for 5 minutes resulting in loss of 3$k unless the robbery would be stopped by killing the one who is robbing it.
-Robbing-
Robbing stores and restaurants, a person would get inside,cuff the NPC Police inside of it and then click the NPC that owns this shop and click "Rob store", it would take around 1 minute and 30 sec. and after that, if the robbery was successful person who robbed he will get:
5k$ from restaurant robbery
3,5k$ from Pawn Shop/Electronic Shop robbery
2k$ from Coffee Shop robbery.
Also will get all stars and crime "Store Robbery" which would take the same amount of time as bank robbery. 
-Stock Selling-
You could buy and sell stocks like in real life buy low sell high, it would be dynamically calculated how much one stock costs and what will happen next either go up or go down and player could make simple legal money from it.

**Comment by Miguimops021** [comment]
its a nice idea, but are interesting too to make a pizza delivery
