### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by Ternzeeh** [broke-protocol/issues#208]
When an admin bans/kicks/arrests someone using the command/removes the job of a player, there should be a warning/pop-up/chat message that only the player can see saying their job is removed etc. When a player gets kicked or banned, a screen message will be displayed saying "You are banned/kicked from the server due to blablabla.." instead of getting sent back to the menu immediately(can also be used when players are kicked automatically due to high ping).

**Comment by UserR00T** [comment]
Disconnect reasons have since been implemented. Thank you for your suggestion!
