### ISSUE TITLE
Mounted Vehicle Weapons

### ISSUE THREAD

**Issue by SergeyMeyer** [broke-protocol/issues#235]
What I mean by this is that perhaps you could make the guns and missles on helis actually shoot and perhaps put a machine gun/50 Cal on the roof of the Humvee that could be used by another player

If needed my discord name is SergeyMeyer

**Comment by Kagemd** [comment]
Nong one day was talking about modeling and how he would have to redesign all the models because there is a "bone" structure to attach the models to. I'm assuming the vehicles are designed the same way.
