### ISSUE TITLE
Pressing 'Refresh' twice (or more) will show the same server multiple times

### ISSUE THREAD

**Issue by UserR00T** [broke-protocol/issues#248]
If you press refresh (main screen) twice or more will show the same server multiple times

Doesn't happen with all servers, and doesn't work everytime.

Screenshot: [https://i.imgur.com/SwnGQuC.png](https://i.imgur.com/SwnGQuC.png)
Video: [https://puu.sh/ya7bp/101ee2c135.mp4](https://puu.sh/ya7bp/101ee2c135.mp4)

**Comment by UserR00T** [comment]
[output_log.txt](https://github.com/DeathByKorea/BrokeProtocol/files/1545806/output_log.txt)
Tried it today and checked output_log.txt, it does create a NullReferenceException,

`NullReferenceException: Object reference not set to an instance of an object`

**Comment by BrokeProtocol** [comment]
Still problem in 0.72

**Comment by UserR00T** [comment]
This has been fixed in 1.0.
