### ISSUE TITLE
0.99$/Free Game.

### ISSUE THREAD

**Issue by ekcja** [broke-protocol/issues#253]
You should make it free or at least cheap, why? I will explain why as I speak, I will give reasons and I will give what may result in my opinion out of it.
REASONS:
1. The game itself is dying, as there still are some people, unfortunately, only some, before the steam update there were around 40 in one server, I mean only one, not looking even at others, without stable community there is no stable game. Every game that mostly depends on multiplayer, requires one stable community, like this one.
2. Updates. If you cannot release updates as often as before, or no updates at all and remain it pay2play there will be less and less people that will try out this game, more negative comments and in the end little to no popularity and sells.
3. Worse and worse reviews, before I could see mostly recommended and now it turned into mixed in the recent reviews. People there have a point, toxic community which I had to deal time ago as I were an administrator.

4. You could make hosting a server paid or something like premium accounts, that could give a player bunch of cosmetics [Coloured name tag, custom clothes etc.] and skins and probably make more out of it.
5. Bigger community,maybe bigger than the beginning on the steam.
6. Better reviews, I saw a large part of the negative reviews talking about how it's a waste to buy this game for 5$, making it 0.99$ or free will certainly be better and things like AI, Mechanics should be reviewed better, because the game is cheap, or free.

This is just my perspective, I may be wrong, I may be right, I just ask you to read and think about this.

**Comment by Cdoggle** [comment]
Adding a few new modes into the game will be amazing.

**Comment by Vixonary** [comment]
Remember that the creator probably needs more money to work on updates and fixes. If the cost was lowered then what is the point of earning?

**Comment by MereGamer** [comment]
A good idea could be to make more updates but smaller, so the community would try new things more often.
