### ISSUE TITLE
Gun license fee costs should be raised

### ISSUE THREAD

**Issue by TENTACLEBOSS** [broke-protocol/issues#266]
The first thing most people try to do in this game is acquire a gun, then accost/shoot people. This means that the first thing people will likely do now is either take a gun from an npc, or more likely go to the town hall and immediately expect to be granted a gun license as soon as they enter the server. 

To encourage players to work towards earning the license, and to get players to do something other than aimless rdm, I propose that the gun license price be raised to at least $1000. This would also offer the advantage of taking some of the burden of granting licenses off of the mayor early on as players would have to spend time, working a job (or by some other means) to earn the necessary money. Right now the fee is so minimal that it is pointless.

**Comment by LightVelox** [comment]
abusers would kill everyone with a license, take them and then be unstopable since no one will be able to get guns at the gunstore anymore, that happened once in the official server
