### ISSUE TITLE
More apartments/houses and rentable shops.

### ISSUE THREAD

**Issue by Lokonln** [broke-protocol/issues#276]
First of all, I'd like to see some more Appartments. Would be cool to have more houses to choose from. Also furniture limit should be increased for Bigger houses, and lowered for smaller houses, and placed bombs, water, food etc. Shouldn't count as a furniture.
Along with that I'd like to see custom shops, that can be rented by one player. The cost per *insert number here* days will determine the amount of stuff and decorations, and guards you can put. After having decorated everything, you'll have to hire Guards, and buy them ammo and weapons. The shopkeeper will have a stockpile of stuff, and he won't replenish it by himself, or else you would have infinite stuff. You'll choose the price and give him how many items you want to sell.
Another thing that would be cool is modding: A blocky version of ArmA would really improve the Roleplay

(count how many times I wrote "Stuff")

**Comment by MereGamer** [comment]
You have good ideas.
