### ISSUE TITLE
More banks/atms, and credit cards

### ISSUE THREAD

**Issue by MereGamer** [broke-protocol/issues#277]
I was thinking with a friend that it would be great if in the BrokeProtocol map there were more banks to be able to steal and use ATM.

Another thing is that it would be great if you can buy a credit card service and you simply have to deposit the money in the bank to use it (The cost of the card would be $ 1000 dollars).

Of course it is necessary that the player can have a record of the expenses with his card, being able to access the account from a mobile, a computer or in the bank.

In case of dying or being arrested it would be great to have a card recovery system in which you have to pay a fee of $ 2500 dollars to create a new one without losing the saved money.

**Comment by TENTACLEBOSS** [comment]
A lot of servers I use already have remote banking so this could be cool. It also raises the question of whether the card should be an item that people can steal. A recovery cost is a good idea, but you could also add an unforgiving element to cards where they are treated like an item that can be stolen. Only a thief would have to know your pin number to use it.

A stolen credit card could be treated by cops as a form of contraband, and to use someone else's credit card they'd have to somehow learn their pin. Just some extra thoughts.

**Comment by MereGamer** [comment]
Another thing that I do not mention before, is that when you buy the credit card you get a random pin, so that at the time you buy, the seller will ask you for the pin.

Why the pin?
In the event that the card is stolen the thief will need the pin, so if the thief does not have the pin he can not access it, and he can`t buy nothing.

**Comment by TENTACLEBOSS** [comment]
I'm pretty sure I said that before.

**Comment by MereGamer** [comment]
Sorry
