### ISSUE TITLE
Nerf Police Job - but not NPCS

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/issues#285]
The job should cost more money to get, like $1500-$2000

Cop Equipment:
- Baton
- Tazer with 5 rounds
- 3 Handcuffs

Remove the pistol mainly to balance the fact gang members don't get shotguns or uzi's anymore. NPC cops should still carry pistols and shotguns however.

Never lose ammo Issue: https://github.com/DeathByKorea/BrokeProtocol/issues/283
Old Post: https://github.com/DeathByKorea/BrokeProtocol/issues/47

**Comment by LightVelox** [comment]
$2000 and you don't have a pistol, tell me how anyone is gonna "fight crime" with that? any idiot will just take a AK47 at the shop and destroy the entire server with no problem
