### ISSUE TITLE
Add "use/action" cooldown upon entering/exiting stores

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/issues#286]
Why does the game need this?
- Players tend to rush into Gun/Pawn store and steal the handcuffs on display and then exit store to reset the NPC cop, then re-entering to immediately handcuff the cop so they can freely gear themselves up for free without any risk. Same can be said about running into the gun store to pick up the rocket launcher and blow everyone up before the NPC can even respond.
- People enter/exit stores to try to avoid being arrested by police, there has been many times I've seen players entering/exiting repeatably while handcuffed to avoid arrest.

I suggest adding a 7-10 second cooldown timer before players can interact with anything, however, the use of weapons should be allowed immediately, to account for people camping stores e.t.c. Will be useful for high latency players as well.

**Comment by Lokonln** [comment]
I suggest to decrease guard's time to respond. They should instantly attack Or arrest the player

**Comment by BrokeProtocol** [comment]
That would be good too, problems will arise with player lag though.
