### ISSUE TITLE
Add Language Localization Support

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/issues#291]
Our community is diverse with many players speaking different languages, I think the playerbase would benefit from having the game translated into their own language. I'm sure there would be people interested in helping translating the game.

New folder in the game directory could be called "locale" then put all the game's phrases in the english file, and then if someone wants to translate the game all they would have to do is create a new file "russian" or "spanish" e.t.c, then have it processed by staff in order for it to be added to the game.

**Comment by UserR00T** [comment]
This has since been implemented. Thank you for suggesting!
