### ISSUE TITLE
Cops + Drivers License

### ISSUE THREAD

**Issue by SergeyMeyer** [broke-protocol/issues#313]
Make police automatically have drivers licenses as the police's job requires a car

**Comment by BrokeProtocol** [comment]
Would make police job more unfair.

**Comment by LightVelox** [comment]
what is unfair is dying in the gunshop and not being able to go back there because you dont have a license, perfect for abusers

**Comment by SergeyMeyer** [comment]
I agree with Light police should get Gun and Drivers licenses as job items. Yet the mayor must accept you for you to become a police officer.

**Comment by Error3000** [comment]
Its pointless, I mean if mayor would have power over who can be police officer then he can basically have his private army which will arrest any player who wants to change it. also police would become more OP that it is now, you dont need driving license to get to the gs, map is small you can easily go there by foot or in the ned just kill npc who has license cuz he has contraband, sry for bad eng

**Comment by HamsterOh** [comment]
I think, the better way is that you need to have the license to get the job.
