### ISSUE TITLE
Shoplifting shouldn't be a crime until you leave the shop

### ISSUE THREAD

**Issue by DeathByKorea** [broke-protocol/issues#32]
Sometimes you pick up an item without meaning it.

Maybe it could have a 'Picking this up is robbery' confirmation

**Comment by ZordX** [comment]
or a 30 second timer that if you don't put it back for 30 seconds it's called shoplifting

**Comment by NongBenz** [comment]
Might be a good idea, though will be finicky to implement, awkward to inform the player, and confusing to police who see you shoplift but can't touch you and just forces a waiting game.
