### ISSUE TITLE
Vote Kicking percentage requirement change

### ISSUE THREAD

**Issue by SergeyMeyer** [broke-protocol/issues#321]
I am not sure if this is true but it seems all players on the server must vote yes for a player to be vote kicked. I think this should be changed to: At least 1/3 of the players on the server must vote and if yes has more votes than the person gets kicked. This is especially helpful with abusive mayors and other abusive players.

**Comment by LightVelox** [comment]
it should be 2/3, 1/3 in a server with 10 people would be just 3 votes, most people just see the voting popup and automatically vote YES, also it would be pretty easy to get some friends to vote yes and ban anyone you dont like in the server

**Comment by Cybermetic** [comment]
i feel the 2/3 would work great for smaller servers
The larger ones though...

**Comment by UserR00T** [comment]
To clear this up, half of the players have to vote 'Yes' to kick the player.
Voting 'No' on the votekick doesn't do anything.

``if (this.gameMan.svNetMan.votedPlayers.Count <= this.gameMan.svNetMan.players.Count * 0.5)``

``this.gameMan.svNetMan.votedPlayers.Count``: Players who voted 'Yes'.
``this.gameMan.svNetMan.players.Count``: Current online players.
`` * 0.5`` devides it by half.

But yes, it should be changed a bit.
