### ISSUE TITLE
Prison key system

### ISSUE THREAD

**Issue by Error3000** [broke-protocol/issues#324]
Right now if you are a police officer and you want to kill one prisoner or search him correctly you need to have 2 prison keys - 1 for going in and 1 for going out I hate it because you can't get prison key from any of the guards in the police station so you have to go all the way to the pawn shop to buy only 1 key.
Maybe make it so 1 key does not waste after one use just like license. I hope the whole thing is not too messy. sry for bad eng

**Comment by LightVelox** [comment]
why would you kill a already arrested prisoner

**Comment by Vixonary** [comment]
For committing crimes inside the prison?

**Comment by UserR00T** [comment]
This will most likely be a feature in BP-Essentials

**Comment by Error3000** [comment]
Reaper/Light if one prisoner grabs a shotgun and starts shooting everyone it becomes a problem cuz he can easily stay there for as long as he wish to, also it makes no sense that guard in prison is always ,,almost dead'' or just handcuffed but you can't fix it without going in.
