### ISSUE TITLE
Vote Kick problem

### ISSUE THREAD

**Issue by Error3000** [broke-protocol/issues#342]
Right now people can vote kick anyone so If most of the serwer know eachother they can votekick everyone  and keep it up as long as they want to do it (I just got kicked with few other people cuz some guys were upset at police) It was probably mentioned in other post but its really annoying, and also the fact that people can spam vote kick is not good.

**Comment by BrokeProtocol** [comment]
Votekick was a useless thing to put in, it really has no place on games where the server player count is greater than 4.

**Comment by Error3000** [comment]
Please delete the ,,vote kick'' option, I can't even play on the serwer cuz there is a group of guys kicking me every time I join.
