### ISSUE TITLE
Objects flying around map

### ISSUE THREAD

**Issue by shadow2345** [broke-protocol/issues#346]
Hello,

I'm watching my girlfriend play the game and the new update messed something up big time. She's playing in offline mode and now everything is glitching out. NPC's are teleporting back and forth and into the sky. Cars are now flying and glitching around. NPC's in cars are going crazy too and looking in funky directions. 

I'll test for it myself soon, but thought I'd mention it.

What we tried: Uninstalling the game and reinstalling (Update wouldn't work without that). Validating files. Restarting the game. 

Side note: Even when update, she had to uninstall the game to play because it said it wasn't updated.

**Comment by BrokeProtocol** [comment]
Have you tried the latest hotfix v0.71a?

**Comment by BrokeProtocol** [comment]
Try going into the Task Manager and setting the process priority of BrokeProtocol.exe to "High", and see if problems go away.

**Comment by BrokeProtocol** [comment]
I think this problem occurs when computer has low amount of available ram.

**Comment by shadow2345** [comment]
Sorry for the late reply

1) Tried that, didn't help
2) Tried that, didn't help either
3) She has 6 gigs of ram

Also, she played fine before the reinforcement update, everything was normal and nothing jumped around. It only started after that update released.

**Comment by BrokeProtocol** [comment]
Thanks for replying, reopened the issue. Could you test the latest release, there was a few hotfixes since the first Reinforcement update.

**Comment by BrokeProtocol** [comment]
Can anyone else reproduce this problem?
