### ISSUE TITLE
Car Owning

### ISSUE THREAD

**Issue by SherlockBones** [broke-protocol/issues#368]
It would be awesome if there was a car dealership and garage attached to it. This would allow players to store "borrowed" cars and buy cars themselves. It also provides a base for future features like crimes for stealing cars and player housing (the same garage could be used for player housing). This is only a suggestion and does not have to be added, i just think it would be cool.

**Comment by TENTACLEBOSS** [comment]
I like this for the most part. If the cars on the map were drastically reduced, it'd incentivize car purchasing and lockpicking, making vehicles a more valuable commodity.

**Comment by Ternzeeh** [comment]
less npc cars driving around town, more buyable cars that will not despawn and only you can use unless you got the key for it or you lockpicked it. Can't think of a way to balance the "it will not despawn" part but I think it's a good idea.
