### ISSUE TITLE
Armed Vehicles completely derail the game.

### ISSUE THREAD

**Issue by hammurabi1337** [broke-protocol/issues#376]
I gave it some time, but my initial fear was correct. The game is legitimately unplayable with the armed vehicles. Any server with more than five or six people is guaranteed to have a instant-killing explosive rampage going at any given time.

I've been trying to police and rp for the last hour and I've been instant killed more than a dozen times. It's relentless. I've dealt with bugs and such in the past but this is a completely different level of sapping my desire to play the game.

**Comment by Error3000** [comment]
lol on the serwer when I play nobody really use them, but I can imagine your pain :/
