### ISSUE TITLE
Motorhome

### ISSUE THREAD

**Issue by CalMack0** [broke-protocol/issues#378]
I think it would be a good idea to add a motorhome, such as an RV. You can customize it and drive it like a normal car, Maybe 2 or 4 seats. You could find it in a car park and pay a fee to have it, such as the tank or military cars.

**Comment by NYANCATZXC** [comment]
ебнутое

**Comment by NYANCATZXC** [comment]
идея

**Comment by UserR00T** [comment]
English only please @NYANCATZXC .

**Comment by NYANCATZXC** [comment]
crappy idea.

**Comment by CalMack0** [comment]
@NYANCATZXC I think it would be a convient way to get around with all your stuff without the risk of dying and losing it all, it would also mean you don’t have to go back to the same destination to get to your home. But each to their own I guess

**Comment by NYANCATZXC** [comment]
how do you imagine it 
where to get and how many of them will be on the server

**Comment by CalMack0** [comment]
@NYANCATZXC I've just edited that in to the thread.
