### ISSUE TITLE
Prevent attacking in the gunstore

### ISSUE THREAD

**Issue by Korolowy** [broke-protocol/issues#380]
The reason for this is to counterbalance people with Criminal and normal earnings. My suggestion is to block the shooting at Ammunation, this should raise the level of Role Play in this game because I have claimed that over 90% of players all the time Camp in Ammunation and kill players who want to buy legally a weapon. It certainly will not affect the game, rather it will introduce another rule.

**Comment by Ternzeeh** [comment]
or when you hold any type of weapon(gun/melee/grenades/etc) while inside the store, the merchant and cop should shoot you on sight. Also maybe add more guards :D
