### ISSUE TITLE
Place a short delay on suiciding when a player is arrested

### ISSUE THREAD

**Issue by TENTACLEBOSS** [broke-protocol/issues#386]
To counteract players immediately commiting suicide when arrested or taken hostage, (and as a result, hurting the rp) the suicide function should be placed on a short delay so that players are unable to instantly resort to killing themselves. 

Clicking the disconnect button should also be subjected to a short cool down every time the Esc key is pressed to prevent players from simply disconnecting to replace the usage of suicide.

**Comment by Ternzeeh** [comment]
+1
