### ISSUE TITLE
Ask Cop to remove cuffs if not wanted

### ISSUE THREAD

**Issue by LightVelox** [broke-protocol/issues#393]
The Npc Cops should have a option for you to ask them to remove the handcuffs from you if you're not wanted, it's a real pain when a npc cuff you for no reason or when someone just trolls you and you need to suicide and lose everything you had, it would make total sense since if a cop probably would free someone from being a hostage or something like it

**Comment by Error3000** [comment]
Sometimes npc cops cuffs you because they are spamming the handcuff option when they are after the criminal so if you get in their way they will just handcuff you, its a pain in the ass

**Comment by PatrykWinner** [comment]
+1 yeah it's annoying,this happened to me when I clicked collect on cash register by mistake instead of buying from store clerk and when my crime ended the npc cops was still chasing me and handcuffed me.
