### ISSUE TITLE
Gun License Problem...

### ISSUE THREAD

**Issue by TecyGuy** [broke-protocol/issues#395]
Basically Gun License's only act as a Pass to the Gun Store and not actually as a License to own a Gun and it's starting to really get to me.
I've been arrested quite a few times by cash hungry cops who think i have "Contraband" On me when in reality i have Clothes, Licenses, Ammo and A gun. in my Inventory, they don't even check.
I already posted this on the steam discussions but it pretty much acts as a Pay X amount to be arrested...
I really think this needs to be fixed or revamped.
It's just an easy way to lose lots of money.

**Comment by PatrykWinner** [comment]
+1,it really annoys me too,i think there should be added some kind of thing when if you got a gun license it shouldn't mark as a contraband,maybe add a penalty (like if they would do it for first time they will get a warning but if it's the third time they will get fired and 3 hours cooldown preventing from joining again to police) to cops if they would to ticket you for gun that you have gun license for.
