### ISSUE TITLE
Some thought's about upcoming SWAT job.

### ISSUE THREAD

**Issue by PatrykWinner** [broke-protocol/issues#397]
**Hello,today I wanted to talk about SWAT job that will be soon relased,and i wan't you to post 
some thoughts about that job too,so we can discuss about that.
My thoughts about that job is:
1.This job should have a npc's but not outside the building because they will be easy target to kill them and stole them gun.
2.This job should have some kind of commander/officer that will manage SWAT member's and make sure that they will not abuse they job.
The Question's is:
1.Where they gonna be having a HQ,in a police station ?,or maybe they will have separate building for swat members.
2.Are they get SWAT vans to drive around or the'y will only have a gear once they join.
What this job will look like for you,post some suggestion's and thought's below :D !.**

**Comment by LightVelox** [comment]
SWAT Members should always be notified of 5-star players and npcs, so they can go and take them out and get a good money for it. that would be a good way of preventing people from abusing the bank

**Comment by PatrykWinner** [comment]
Yeah but at the time when nobody from the player's and npc's got 5 star's wanted level,the swat member's should be at their HQ.
I think that they should have some kind of commander that would train them,and if you would be new in SWAT then you must go to training and learn and if you would pass then your rank would change by swat officer,so for me they would need to get some ranks in this job,so nobody would abuse criminal's and citizen's because they are supervisor's who can get them fired.

**Comment by Error3000** [comment]
I think that when SWAT player or npc is killed he doesn't drop any weapons or stuff, he only drops the stuff that he is not getting when getting the job. I think that that would prevent people from suicide ->friend grabs the SWAT stuff ->repeat
