### ISSUE TITLE
Bug: Cannot open Interface for objects or people

### ISSUE THREAD

**Issue by PixelAdventures** [broke-protocol/issues#406]
Sometimes, mostly when i enter an Apartment, I can still open the Interface with 'Cancel', 'Equipment' and 'My Crimes' , but if I try to, for instance, Show a persons Crimes, or Intimidate them, it doesn't highlight them, neither does the options show up, just the said three. This also prevents from picking up items in my own Apartment.

**Comment by UserR00T** [comment]
Yeah sometimes it doesn't select the object while looking at it, thanks for reporting!

**Comment by NongBenz** [comment]
This bug should've been fixed in previous updates. If it crops up again, please repost.
