### ISSUE TITLE
BUG: No Money in Gangster Jobs

### ISSUE THREAD

**Issue by Cobyrk** [broke-protocol/issues#426]
All of the gang jobs currently receive no income for having territory, killing rival gang members, or taking land from other gangs.

Currently, there's no real reason to join the gangs other than to keep some of the medium tier weapons when you die.

**Comment by NongBenz** [comment]
I'm removing 'bug' on this since it was intended to prevent easy idling money. No other job gets passive income so gangsters are instead rewarded for gang war kills. Jobs do need more work and balancing however.
