### ISSUE TITLE
Free food

### ISSUE THREAD

**Issue by Tatitooo** [broke-protocol/issues#456]
**Describe the bug**
The bug lets the user get free food from nowhere.

**To Reproduce**
1. Become a Delivery Driver
2. Wait to get a Deliver order
3. Disconnect
4. Connect to the game and now you have 2 food items in your inventory.

**Expected behavior**
Should delete the order and the item of the order when the user disconnects.

**Screenshots**
![image](https://user-images.githubusercontent.com/23179501/69000630-7990fc80-08b1-11ea-84e5-33a2acaf5dc9.png)
![image](https://user-images.githubusercontent.com/23179501/69000634-84e42800-08b1-11ea-8a58-c0438c190b74.png)

**Comment by PLASMAchicken** [comment]
#385 #444 already spoke about this

**Comment by Tatitooo** [comment]
thats true, sorry.
