### ISSUE TITLE
teleport glitch

### ISSUE THREAD

**Issue by LOLMANLIKEPIE** [broke-protocol/issues#461]
**Describe the bug**

**To Reproduce**
1. Go to any door 
2. walk in
3. hold in s
4. you will teleport to a new location

**Expected behavior**
the walk in to a wall

**Comment by PLASMAchicken** [comment]
Basically, when doing that, the wall does not load fast enough and you will be able to walk trough it, you will then fall below the map and will be teleported there where you last logged out. 

Unconfirmed but:
This may also be a server crasher, by making it repeat the teleportation endlessly, eg. jumping trough the wall, disconnecting to save the pos, relogging and waiting until you get teleported so often that the Server may struggle

**Comment by LOLMANLIKEPIE** [comment]
![evidence](https://user-images.githubusercontent.com/59487205/71748712-af933b80-2e73-11ea-8c93-bca0df33b209.png)
can also let you do this in the game
