### ISSUE TITLE
Mobile 1.03 Connect

### ISSUE THREAD

**Issue by Kiczan1337** [broke-protocol/issues#464]
Cannot connect to any server
![Screenshot_20200206-151056](https://user-images.githubusercontent.com/33396850/73947250-7416e180-48f7-11ea-8122-cc32bc319723.jpg)

**Comment by NongBenz** [comment]
Fixed in 1.03 updates. If still can't connect, normally due to poor connection, permissions, or server not updated with hotfixes.
