### ISSUE TITLE
If restrained(handcuffed) you cannot prevent others from searching you

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/issues#57]

**Comment by UserR00T** [comment]
a little bit late ;3

I think that is not a good idea, because people can just handcuff you and steal your stuff (even if you are cop etc)

**Comment by notafed** [comment]
I agree with this in general, only if handcuffing people weren't so easy. Give it a progress bar or something to give a player to react, handcuffing shouldn't be instant.
