### ISSUE TITLE
Make usernames case-insensitive

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/issues#61]
So you can't pretend to be someone else. You can create different accounts with the same name, ex: NewGuy - NEWGUY - Newguy - newguy e.t.c

However, if you do want to change the casing of your user name, all you would have to do is adjust it accordingly and use the same password.

**Comment by UserR00T** [comment]
We've decided to allow collisions in 1.0 and to differentiate players we use the first x characters of your steamid.
