### ISSUE TITLE
Allow rotating camera with mouse while knocked out

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/issues#68]

**Comment by UserR00T** [comment]
Ehum, this is already in the game, right?

**Comment by BrokeProtocol** [comment]
It's not.

**Comment by UserR00T** [comment]
[https://puu.sh/yoyjJ/31d38a2474.mp4](https://puu.sh/yoyjJ/31d38a2474.mp4) (Using arrow keys)

**Comment by BrokeProtocol** [comment]
You should be able to move it with your mouse. The arrow keys are buggy, and constantly zoom you out when adjusting the camera.
