### ISSUE TITLE
Anti Cop RDM System

### ISSUE THREAD

**Issue by Alfa1561** [broke-protocol/issues#79]
An idea for a system to stop RDMing cops would be to instantly remove all cop gear from a cop who keeps committing crimes, say he racks up multiple charges for armed assault in a short amount of time. All the items, uniform and weapons, disappear from the RDMing cops, and they get auto banned from rejoining the police for another 10-15 minutes

**Comment by LightVelox** [comment]
someone try to attack player cop, player cop react before being killed, player cop get banned

makes sense

**Comment by Error3000** [comment]
Light, If someone is attacking cop it means that he has a crime star co the cop can just kill him easily. The whole idea makes sense.
