### ISSUE TITLE
Business robbery alarms, remove shop guards

### ISSUE THREAD

**Issue by Alfa1561** [broke-protocol/issues#81]
Put alarms in businesses you can rob and remove the guards. Except for the bank, bank guards make sense. The alarm should possibly put a marker on player cop's map to respond to a robbery so they can try intercept the criminal etc

**Comment by DarkRosanne** [comment]
I'm not sure if removing the guards is a good idea really. Gunstore definatly should keep a guard but the cafe, pawnshop and fast food place I can understand not having a guard but having an alarm only instead.
They all should have an alarm though if the shopkeeper is getting stolen from or being cuffed or something along those lines.
