### ISSUE TITLE
Drunk Animation

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/issues#95]
When you are intoxicated your character will do the Drunk Walking Animation, also your controls will be inverted or randomized for full effect. Could be reused for other consumables such as drugs.

**Comment by DarkRosanne** [comment]
Maybe make it so like when your walking it randomly walks in other directions to give a feeling of a stumbling walk. Example: walking forward and it tugs left and right occasionally at different strengths meaning you have to combat it with pressing the opposite direction.
For drugs I think the disorientation works for now personally.
