### ISSUE TITLE
[Gang System Improvement] Sprays, graffiti, DW41 and small destruction system

### ISSUE THREAD

**Issue by Brodatv** [broke-protocol/issues#96]
So, I've decided to destribe my idea and write some stuff about feature that I would like to see in Broke Protocol. If you want to comment my idea, it's better to @ me on Discord - \@Brodaty - you should find me near always online.

Playing 0.652 and beeing a gang member isn't so much fun after dying with full EQ. It would be great to make it less aggressive, or a little more advanced.  So far playing as gang member is just about making turf wars. It's not very profit-able. How about graffiti? Let me describe this idea :)

## New items:

**Spray Can**
Cost - 50$
Isn't working as contraband
One use / one charge
Avaiable in Pawn Shop, Coffee Shop and Drug Dealer (1 for every faction)
Weight: 1kg

**DW41**
Cost - 50$
Isn't working as contraband
One use / one charge
Avaiable in Pawn Shop, Coffee Shop and Drug Dealer (1 for every faction)
Weight: 1kg

## Regions avaiable to spray

(it's just idea and proposal)
**Red zone**: Walls between hospital and fire station (3 locations), walls near the port in bank area (2 locations)
**Blue zone**: Walls near Burger Shop (3 locations), walls on the parking zone (2 locations)
**Green zone**: Walls on the sea side near Drug Dealer (3 locations), walls between houses near green gang leader (2 locations)

## Why I need spray or DW41?

**Finding locations to spray**. It should look different than background, for example like place where someone was trying to remove paint using some kind of detergent. Example here - [http://i.imgur.com/nloZIFr.jpg](url)

**Spraying as gang member** - you can use one Spray can on one wall and spray your gang tag or gang slang here.  It should work like normal graphic image that game is "overlay'ing" on house or wall.  Every gang is able to spray 15 locations - 5 own and 10 in enemy regions. First you have to remove other gang tag using DW 41 and then you can spray your own. Also, this works like violation - Vandalism - 500$ fine, 2 minutes in prison and 2:00 search time, 1 star, so police is trying to cuff you first. Second spray is +1 star, so they will try to shoot you.

Every tag is granting 3$ more to your gang earnings. So if gang is earning 40$ in base form, all 15 locations sprayed will earn you 85$ every some minutes. By capturing more regions gangs are able to earn even more. 

**Removing tags as firefighter** - so far firefighter job should be nerfed realy hard and they should get another job. 300 for one fire is HORRIBLY too much, it should be approx 100-150 for each fire. The police have a lot of options, same medics, but firefighters are not so advanced. That's the reason why they should use DW41 to remove sprays and get 70$ for each tag.

## Anti-money-farm

Also we need to think about some security. People will be farming money - one player is gonna clean it, another one is spraying all the time... **HELL NO!**.
Using WD41 just after spraying:
_Paint is still wet, you have to wait until tag will be dry._   (5 minutes)
Using spray on enemy tag:
_You need to remove old tag first, use WD41 when paint is dry._

## Destruction system

It would be great to get something more than just a melee weapon after respawn, when player is working as gang member. That's the reason why I'm writing destruction idea linked with gang system. How about making some kind of destruction in enemy regions?

Example - using melee weapons you can destroy windows and stuff placed in a front of shop in enemy region.  It would be great to see some stalls and benches in front of the shops that you can destroy. How it works and where to find them?

**Blue Region** - Burger Shop
**Red Region** - Coffee Shop
**Green Region** - We need something more here... Imho Green Region is underpowered in shops or something like that.

## How to repair destroyed stalls, payment for it and anti-money-farm

Everyone can use **Drill**, **Repair Kit** or **Wrench** to repair stalls. It takes 5 secs to finish it and job is granting 100$ to firefighter, medic or policeman that started repairing and finished it. **Also, it can't be repaired before 5 mins** from destruction.
_Stalls were destroyed too early, you have to wait to fix them._

## Reward for destroyed stals as gang member

First of all, using weapon, even punch on shop stall is a crime:
Destruction, 4:00, 1000$ fine and 2 stars, so police is shooting at once.

If you **control your own** shop stand you can buy Tazer Ammo using Gang Leader.

You have to control your own shop stand to get next rewards, if your shop stall is destroyed you are losing profits until it is repaired. So if enemy will repair their shop stand you lose one feature avaiable below.

If your gang **destroyed one enemy shop stand** you can buy 5 pistol ammo using Gang Leader. It respawns over time, but no more than 5 at once.
If your gang **destroyed two enemy shop stands** you can buy one Riot Armor using Gang Leader. PRICE IS HIGHER than in Gunshop. It respawns over time, but no more than 1 at once.

## Text and messages

**IF** normal citizen is trying to break shop stand:
Simply... no message :D RPG style! So he can't mess in destruction system without beeing gang member.
**IF** own shop stall is repaired:
Your gang repaired shop stand. Tazer ammo avaiable at Gang Leader.
**IF** one enemy shop is destroyed by player gang members:
One enemy gang shop stall destroyed. Pistol ammo avaiable at Gang Leader.
**IF** two enemy shops are destroyed by player gang members:
Two enemy gang shop stalls destroyed. Riot Armor avaiable at Gang Leader.
**IF** enemy player gang lost their shop stall:
Our shop stall near X was destroyed by Z. --- where X is player gang and Z is enemy gang

**Comment by BrokeProtocol** [comment]
Excellent ideas and details. I'd like to see all of it added into the game, would fit in nicely with the theme of game. Thanks for the time and effort you have put in to write up a well written entry!
