### ISSUE TITLE
Voice Chat icon pop-up

### ISSUE THREAD

**Issue by PunInABun** [broke-protocol/issues#97]
I've been playing the game and the main thing that confuses people is if they are actually voice chating or not, so i sugest that when you click the voice chat button, a little icon pops-up and goes away when you stop talking, thanks!

**Comment by DarkRosanne** [comment]
I think this should be done 'Rust' Style where it shows in the bottom corner or top corner who is talking, but not above them with a symbol.
Reason being: If your crowched or something the symbol gives your position away which is an unfair advantage to some.
